UPDATE Songs SET PoetBookTitle='Peak’s New Collection', Poet1Date='1793' WHERE PageNum='80t';
UPDATE Songs SET PoetBookTitle='Battle’s Collection', Poet1Date='1814' WHERE PageNum='104';
UPDATE Songs SET PoetBookTitle='The Baltimore Collection', Poet1Date='1801' WHERE PageNum='144';
UPDATE Songs SET PoetBookTitle='Purify’s Selection of Hymns', Poet1Date='1826' WHERE PageNum='157';
UPDATE Songs SET PoetBookTitle='Vedder’s Selection', Poet1Date='1827' WHERE PageNum='170';
UPDATE Songs SET Poet1First='Samuel', Poet1Last='Crossman', Poet1Date='1664' WHERE PageNum='185';
UPDATE Songs SET Poet1First='Nahum', Poet1Last='Tate', Poet1Date='1700' WHERE PageNum='186';
UPDATE Songs SET Poet1First='John Adam', Poet1Last='Grande', Poet1Date='1801' WHERE PageNum='201';
UPDATE Songs SET PoetBookTitle='Southern And Western Harmonist', Poet1Date='1845' WHERE PageNum='206';
UPDATE Songs SET Poet1First='Samuel', Poet1Last='Crossman', Poet1Date='1664' WHERE PageNum='208';
UPDATE Songs SET PoetBookTitle='Abner Jones’s Melody Of The Heart', Poet1Date='1804' WHERE PageNum='210';
UPDATE Songs SET Poet1First='Isaac', Poet1Last='Watts', Poet1Date='1719' WHERE PageNum='211';
UPDATE Songs SET PoetBookTitle='Joshua Smith’s Divine Hymns', Poet1Date='1794' WHERE PageNum='266';
UPDATE Songs SET Poet1First='John', Poet1Last='Cennick', Poet1Date='1741' WHERE PageNum='271b';
UPDATE Songs SET Poet1First='Philip', Poet1Last='Doddridge', Poet1Date='1775' WHERE PageNum='279';
UPDATE Songs SET PoetBookTitle='Wakefield’s The Christian Harp', Poet1Date='1837' WHERE PageNum='285b';
UPDATE Songs SET Poet1First='John', Poet1Last='Ellis', Poet1Date='1838' WHERE PageNum='341';
UPDATE Songs SET Poet1First='Frances R.', Poet1Last='Havergal', Poet1Date='1878' WHERE PageNum='493';
